--- 
before_script: 
  - "npm install -g ionic cordova"
branches: 
  only: 
    - master
deploy: 
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: www
  provider: pages
  skip-cleanup: true
  true: 
    branch: master
language: node_js
node_js: 
  - "8.12.0"
script: 
  - "ionic cordova build browser -prod"
  - npm run test:ci
  - npm run lint
notifications:
  email:
    recipients:
      - dvalax.pro@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
